### ISSUE TITLE
Backoffice - hookDisplayAdminOrderContentOrder problem

### ISSUE THREAD

**Issue by carmas123** [202-ecommerce/stripe_official#64] opened 2021-05-24 13:26 UTC
There is a problem with 1.7.7.4 version of Prestashop, when we open an order into backoffice the template is not rendered.
After some investigation I see that we need to change at row 1350 of "stripe_official.php"

FROM:
```
        $stripePayment = new StripePayment();
        $stripePayment->getStripePaymentByCart($params['order']->id_cart);
```

TO
```
        $order = new Order($params["id_order"]);
        $stripePayment = new StripePayment();
        $stripePayment->getStripePaymentByCart($order->id_cart);
```

This permit to have valid smarty parameters assignment.
After that we cannot already see the correct tab:

![image](https://user-images.githubusercontent.com/6574219/119354365-4ef0e280-bca4-11eb-9da5-2214d20e4f45.png)

This is because also into the hookDisplayAdminOrderTabOrder the $params does not contain "order" child, but only "id_order" and after whe have changed it to (at row 1334):

```
        $order = new Order($params["id_order"]);
        if ($order->module != 'stripe_official') {
            return;
        }
```

now all work fine.

![image](https://user-images.githubusercontent.com/6574219/119355345-709e9980-bca5-11eb-8fd7-0c81c3679c10.png)

**Comment by mribeiro202** [comment] 2021-05-24 14:24
Hello @carmas123 

We are going to reproduce and correct this bug. 
Thank you for your help.

**Comment by mribeiro202** [comment] 2021-06-28 14:49
Hi @carmas123 
The latest version of Stripe (v2.3.2) is now available, since this afternoon. Maybe you could try to update the module, we have corrected this problem.

Have a nice day.

**Comment by mribeiro202** [comment] 2021-09-06 15:56
Hi @carmas123 

I take the liberty of closing this issue, do not hesitate to reopen if necessary.

Have a nice day

**Closed by mribeiro202** 2021-09-06 15:56 UTC
