### ISSUE TITLE
Source::retrieve failed when the conveyor token is a card

### ISSUE THREAD

**Issue by JimmyBillan** [202-ecommerce/stripe_official#111] opened 2022-01-19 11:19 UTC
Hello, 
We are seeing a lot of uncaptured payement for some users, the code seems to fail when ValidationOrderActions::createOrder() try de retrieve the source from a card.

```php
if (strpos($this->conveyor['token'], 'pm_') !== false) {
            $this->conveyor['payment_method'] = \Stripe\PaymentMethod::retrieve($this->conveyor['token']);
            $this->conveyor['datas']['type'] = $this->conveyor['payment_method']->type;
            $this->conveyor['datas']['owner'] = $this->conveyor['payment_method']->billing_details->name;
} else {
            // Retrieve fail when the $this->conveyor['token'] is a "card_XXXX"
            $this->conveyor['source'] = \Stripe\Source::retrieve($this->conveyor['token']);
            $this->conveyor['datas']['type'] = $this->conveyor['source']->type;
            $this->conveyor['datas']['owner'] = $this->conveyor['source']->owner->name;
 }
```

As a quickfix i i would like to test if the token start with 'card_' :
```php
if (strpos($this->conveyor['token'], 'pm_') !== false) {
   ...
   }
else if (strpos($this->conveyor['token'], 'card_') !== false) {
          $this->conveyor['datas']['type'] = "card";
          $this->conveyor['datas']['owner'] = "";
 }else {
          $this->conveyor['source'] = \Stripe\Source::retrieve($this->conveyor['token']);
          $this->conveyor['datas']['type'] = $this->conveyor['source']->type;
         $this->conveyor['datas']['owner'] = $this->conveyor['source']->owner->name;
}

 ```
 I don't see where the 'owner' value is used. 
 
https://github.com/202-ecommerce/stripe_official/blob/develop/classes/actions/ValidationOrderActions.php#L298

**Comment by clotairer** [comment] 2022-01-19 11:32
Hi @JimmyBillan 

Thank you for your suggestion. I think your case can help us to fix this bug we cannot reproduce.
Do you have a testing environment we could use together ?


Thank you

**Comment by JimmyBillan** [comment] 2022-01-19 11:49
Hi @clotairer 

Sadly no, we are facing this issue only in production. Impossible to reproduce. 
Customer #1 : uncaptured with card 3007 (card_)
Customer #1 : uncaptured with card 3007 (card_)
Customer #1 : uncaptured with card 3007 (card_)
Customer #1 : **captured** with card 6903 (DIFFERENT CARD)

And an other Customer that keep the same card : 
Customer #2 : uncaptured with card 8317 (card_)
Customer #2 : uncaptured with card 8317 (card_)
Customer #2 : **captured** with card 8317 (SAME CARD but became a pm_)

I don't understand why the convoyer got a payement method and sometime de card

**Comment by clotairer** [comment] 2022-01-19 12:34
You have logs on stripe_official_processlogger of all and a [controller to view logs](https://domain.tld/adminXXX/index.php?controller=AdminStripe_officialProcessLogger&configure=stripe_official)

@Afayadas and me can help you to analyse data. Could you please send me a message on the [support addons page](https://addons.prestashop.com/en/contact-us?id_product=24922) (with @clotairer and github issue 111). I'll send you my email to share "private" data.

Thank you.

**Comment by clotairer** [comment] 2022-02-25 15:14
Hi,

**Comment by clotairer** [comment] 2022-02-25 15:18
Hi
We rework on you issue today. Unfortunately we can't reproduce your issue. Do you have any new cases ?
Do you have a sample Json for a payment prefixed by "card_" ?

**Comment by JimmyBillan** [comment] 2022-02-25 16:18
Hello Clotaire.
We can't reproduce :( its not happening anymore. The quickfix we added in the first message is not called anymore.

`else if (strpos($this->conveyor['token'], 'card_') !== false) {`

The $this->conveyor['token'] doesn't seems to be a "card_XXX" anymore. It used to happen for small part of our client (less than 10%). 
We don't know why the token became a card_  and we don't know why it stop.

**Comment by clotairer** [comment] 2022-02-25 16:24
OK I propose to close this issue now. You can reopen it if this the case append again.

Thank you.

**Closed by clotairer** 2022-02-25 16:24 UTC
Labels: bug
