### ISSUE TITLE
Upon entering card details, error occurs for some customers

### ISSUE THREAD

**Issue by githubjonny** [202-ecommerce/stripe_official#120] opened 2022-02-15 15:32 UTC
PS 1.7.8.3

For all UK orders, everything seems to be working fine. However for some non UK orders, we are seeing the below error:

"This PaymentIntent’s payment_method_types could not be updated because it has a status of requires_capture. You may only update the payment_method_types of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action."

**Comment by clotairer** [comment] 2022-02-15 15:35
Hi thank you for your report.

Is it the same bug than #118 ?

**Comment by githubjonny** [comment] 2022-02-15 15:37
Not sure (error is different but may be related), the payment occurs when paying via a card.

**Comment by githubjonny** [comment] 2022-02-15 15:41
Looking in stripe we can see a 400 ERR "A request to update a paymentIntent XXXXXXXXXXXXXXX failed"  with the code in the response of:
"code": "payment_intent_unexpected_state",
"doc_url": "https://stripe.com/docs/error-codes/payment-intent-unexpected-state",
"message": "This PaymentIntent's payment_method_types could not be updated because it has a status of requires_capture. You may only update the payment_method_types of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action.",

**Comment by clotairer** [comment] 2022-02-15 15:46
Do you use option Authorize and Catch ? You use 2.4.2 version of the module ?

**Comment by githubjonny** [comment] 2022-02-15 15:54
All settings in the module are default with the exception :
"Display an extended version of the form with card logos instead of the compact version. Choose the logos to display below based on the brands accepted by your Stripe account."
is ticked.

No action is usually required by us to complete the payment (e.g. should be auto Authorized) and other payments since (all UK) have gone through fine.

Module V 2.4.2

talking to stripe now to see if they can shed any light.

Have already replied to an old ticket with prestashop (Thread #725025) but will add your details to end.

**Comment by githubjonny** [comment] 2022-02-15 16:23
From Stripe:

My team could determine that: it seems that the country was not the issue.

On the first attempt, customer's card was declined. Then the card was changed and that was confirmed successfully. But then instead of finishing the checkout and capturing the funds, the customer was left on the checkout page. I would suggest that you contact Prestashop plugin for further assistance.

**Comment by ecenturyuk** [comment] 2022-02-15 16:23
Yes a client has reported same bug after upgrade to 2.4.2

I think it could be related to using Android and details filled in with GPay

Please see attached screenshot

![screenshot_2](https://user-images.githubusercontent.com/87011426/154104046-df539d6b-7d58-4e36-b859-e628b6e58e6f.jpg)

**Comment by githubjonny** [comment] 2022-02-15 16:24
Our customer was using a windows device and not Gpay. Do you know if your clients customer had a failed transaction first?

**Comment by ecenturyuk** [comment] 2022-02-15 16:36
ok thanks for that

Yes there was a failed payment initially so that could be it

And then a lot of this error

Error message
"message": "This PaymentIntent's payment_method_types could not be updated because it has a status of requires_capture. You may only update the payment_method_types of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action."
"type": "invalid_request_error"

**Comment by githubjonny** [comment] 2022-02-15 16:39
Same here. 1 failed payment then 6 of :

"message": "This PaymentIntent's payment_method_types could not be updated because it has a status of requires_capture. You may only update the payment_method_types of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action."
"type": "invalid_request_error"

**Comment by clotairer** [comment] 2022-02-15 16:42
Thank you for these elements. We will try to reproduce.
@githubjonny we received your message. Keep in touch.

**Comment by clotairer** [comment] 2022-02-17 15:05
Hi
We make some tests, it looks like the pull request #119 fixed this issue.
Thank you

**Comment by jgriff321** [comment] 2022-02-18 10:33
Hi we also have this issue and appreciate the fix is in progress. To elaborate on the issue, it occurs when a customer enters wrong payment details. They then get the error message  "This PaymentIntent's payment_method_types could not be updated because it has a status of requires_capture. You may only update the payment_method_types of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action." on checkout. 

This occurs if they enter wrong CVC, then try to update it, wrong card number, wrong expiry. They then can't place any order using this cart at all and have to delete cart and start again then use different payment method. 

Can we use the changes in pull request now to fix the issue before the new module update is released?

**Comment by githubjonny** [comment] 2022-02-28 11:03
Can you please confirm the changes needed to fix this issue as we are still seeing this issue occur

**Comment by githubjonny** [comment] 2022-02-28 11:06
is it just the 1 line change on https://github.com/202-ecommerce/stripe_official/pull/119/commits/af5e1d3376936a03abb7cca46a524a4fd7a02726 ?

**Comment by clotairer** [comment] 2022-02-28 11:09
Hi,
This issue is linked to this PR:
https://github.com/202-ecommerce/stripe_official/pull/124/files

Thanks

**Comment by githubjonny** [comment] 2022-02-28 11:15
Hello @clotairer Do you know when the module will be updated? 
Also is the change on https://github.com/202-ecommerce/stripe_official/commit/af5e1d3376936a03abb7cca46a524a4fd7a02726 a tempoary fix which the changes on https://github.com/202-ecommerce/stripe_official/pull/124/files hopefully the permenant fix?

**Comment by clotairer** [comment] 2022-02-28 11:20
The PR https://github.com/202-ecommerce/stripe_official/commit/af5e1d3376936a03abb7cca46a524a4fd7a02726 was proposed by the community but doesn't fix all cases.
The next release is not schedule for now. If you contact our [support](
https://addons.prestashop.com/en/contact-us?id_product=24922) we will supply a fix before the next release. Just indicate the issue 120 on Github.

**Comment by clotairer** [comment] 2022-03-02 17:18
Hi,

You can download the (pre)release [2.4.3](https://github.com/202-ecommerce/stripe_official/releases/tag/2.4.3) or wait the availability on PrestaShop Addons.

Thank you.

**Closed by clotairer** 2022-03-02 17:18 UTC
